apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: colorless-days-children
  annotations:
    kubernetes.io/ingress.global-static-ip-name: colorless-days-children
    networking.gke.io/managed-certificates: serg-vlassiev-info
    networking.gke.io/v1beta1.FrontendConfig: https-redirect
  labels:
    app: colorless-days-children
spec:
  defaultBackend:
    service:
      name: colorless-days-children
      port:
        name: http
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: colorless-days-children
                port:
                  name: http
          - path: /hiking/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: hiking
                port:
                  name: http
          - path: /hiking-api/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: hiking-api
                port:
                  name: http
          - path: /hiking
            pathType: ImplementationSpecific
            backend:
              service:
                name: hiking
                port:
                  name: http
          - path: /css/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: hiking
                port:
                  name: http
          - path: /js/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: hiking
                port:
                  name: http
          - path: /favicon.ico
            pathType: ImplementationSpecific
            backend:
              service:
                name: hiking
                port:
                  name: http
